CREATE TYPE affected_entity_type AS ENUM ('task');
CREATE TYPE edge_type AS ENUM ('bridge', 'common');
CREATE TYPE game_event_type AS ENUM ('edge_break', 'interaction_acceleration', 'move_acceleration', 'neutralize', 'simple', 'teleportation');
CREATE TYPE game_screen_mode AS ENUM ('full_screen', 'window');
CREATE TYPE question_type AS ENUM ('location', 'stakeholder', 'task', 'worker');
CREATE TYPE resource_type AS ENUM ('risk', 'tool');

CREATE TABLE IF NOT EXISTS action_area
(
    id              uuid                  NOT NULL,
    path_to_texture character varying(50) NOT NULL,
    name            character varying(30) NOT NULL,
    CONSTRAINT "PK_action_area" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS affected_entity
(
    id                   uuid                 NOT NULL,
    affected_entity_type affected_entity_type NOT NULL,
    CONSTRAINT "PK_affected_entity" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS brief_info
(
    id                 uuid    NOT NULL,
    quest_id           uuid    NOT NULL,
    is_true            boolean NOT NULL,
    affected_entity_id uuid    NOT NULL,
    text               text    NOT NULL,
    CONSTRAINT "PK_brief_info" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS district
(
    id               uuid                  NOT NULL,
    research_area_id uuid                  NOT NULL,
    name             character varying(50) NOT NULL,
    description      text                  NOT NULL,
    CONSTRAINT "PK_district" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS edge
(
    id         uuid      NOT NULL,
    node1_id   uuid      NOT NULL,
    node2_id   uuid      NOT NULL,
    event_type edge_type NOT NULL,
    CONSTRAINT "PK_edge" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS event
(
    id                   uuid                  NOT NULL,
    district_id          uuid,
    research_area_id     uuid                  NOT NULL,
    event_type           game_event_type       NOT NULL,
    is_positive          boolean               NOT NULL,
    name                 character varying(50) NOT NULL,
    description          text                  NOT NULL,
    time_delay_in_minute smallint              NOT NULL,
    chance               real                  NOT NULL,
    max_occurance_count  smallint              NOT NULL,
    event_data           jsonb                 NOT NULL,
    CONSTRAINT "PK_event" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS health_phrases
(
    id         uuid    NOT NULL,
    text       text    NOT NULL,
    show_count integer NOT NULL,
    CONSTRAINT "PK_health_phrases" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS icon
(
    id   text  NOT NULL,
    body bytea NOT NULL,
    CONSTRAINT "PK_icon" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS info_source
(
    id                   uuid                  NOT NULL,
    research_area_id     uuid                  NOT NULL,
    name                 character varying(50) NOT NULL,
    info_text            text                  NOT NULL,
    info_source_level_id uuid                  NOT NULL,
    CONSTRAINT "PK_info_source" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS info_source_levels
(
    id                      integer GENERATED BY DEFAULT AS IDENTITY,
    interact_time_in_minute smallint NOT NULL,
    CONSTRAINT "PK_info_source_levels" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS info_source_quest_resource
(
    id             uuid NOT NULL,
    info_source_id uuid NOT NULL,
    resource_id    uuid NOT NULL,
    CONSTRAINT "PK_info_source_quest_resource" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS location
(
    id             uuid                  NOT NULL,
    action_area_id uuid                  NOT NULL,
    name           character varying(50) NOT NULL,
    path_to_icon   character varying(50) NOT NULL,
    CONSTRAINT "PK_location" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS neutralizer
(
    id           uuid                  NOT NULL,
    name         character varying(50) NOT NULL,
    path_to_icon character varying(50) NOT NULL,
    CONSTRAINT "PK_neutralizer" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS node
(
    id          uuid NOT NULL,
    district_id uuid NOT NULL,
    CONSTRAINT "PK_node" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS obstacle
(
    id                   uuid                  NOT NULL,
    research_area_id     uuid                  NOT NULL,
    name                 character varying(50) NOT NULL,
    description          text                  NOT NULL,
    time_delay_in_minute smallint              NOT NULL,
    max_instance         smallint              NOT NULL,
    path_to_icon         character varying(50) NOT NULL,
    CONSTRAINT "PK_obstacle" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS passed_quests
(
    id       uuid     NOT NULL,
    save_id  uuid     NOT NULL,
    quest_id uuid     NOT NULL,
    score    smallint NOT NULL,
    CONSTRAINT "PK_passed_quests" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS player_settings
(
    id           uuid             NOT NULL,
    player_id    uuid             NOT NULL,
    screen_mode  game_screen_mode NOT NULL,
    music_volume smallint         NOT NULL,
    sfx_volume   smallint         NOT NULL,
    text_speed   smallint         NOT NULL,
    CONSTRAINT "PK_player_settings" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS quest
(
    id                  uuid                  NOT NULL,
    name                character varying(50) NOT NULL,
    description         text                  NOT NULL,
    parent              integer               NOT NULL,
    stakeholder_id      uuid                  NOT NULL,
    research_area_id    uuid                  NOT NULL,
    action_area_id      uuid                  NOT NULL,
    max_questions_count smallint              NOT NULL,
    CONSTRAINT "PK_quest" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS quest_event
(
    id               uuid NOT NULL,
    event_id         uuid NOT NULL,
    research_area_id uuid NOT NULL,
    CONSTRAINT "PK_quest_event" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS quest_obstacle
(
    id               uuid NOT NULL,
    obstacle_id      uuid NOT NULL,
    research_area_id uuid NOT NULL,
    CONSTRAINT "PK_quest_obstacle" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS quest_resource
(
    resource_id   uuid                  NOT NULL,
    quest_id      uuid                  NOT NULL,
    name          character varying(50) NOT NULL,
    resource_type resource_type         NOT NULL,
    CONSTRAINT "PK_quest_resource" PRIMARY KEY (resource_id)
);

CREATE TABLE IF NOT EXISTS quest_source_info
(
    id               uuid NOT NULL,
    quest_id         uuid NOT NULL,
    research_area_id uuid NOT NULL,
    info_source_id   uuid NOT NULL,
    CONSTRAINT "PK_quest_source_info" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS quest_workers
(
    id        uuid NOT NULL,
    worker_id uuid NOT NULL,
    quest_id  uuid NOT NULL,
    CONSTRAINT "PK_quest_workers" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS questions
(
    id            uuid          NOT NULL,
    quest_id      uuid          NOT NULL,
    parent_id     uuid,
    content       text          NOT NULL,
    answer        text          NOT NULL,
    question_type question_type NOT NULL,
    CONSTRAINT "PK_questions" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS questions_info
(
    id            uuid          NOT NULL,
    question_id   uuid          NOT NULL,
    brief_info_id uuid          NOT NULL,
    question_type question_type NOT NULL,
    CONSTRAINT "PK_questions_info" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS research_area
(
    id              uuid                  NOT NULL,
    path_to_texture character varying(50) NOT NULL,
    CONSTRAINT "PK_research_area" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS risk
(
    resource_id    uuid NOT NULL,
    neutralizer_id uuid NOT NULL,
    location_id    uuid NOT NULL,
    description    text NOT NULL,
    path_to_icon   text NOT NULL,
    CONSTRAINT "PK_risk" PRIMARY KEY (resource_id)
);

CREATE TABLE IF NOT EXISTS save
(
    save_id uuid                     NOT NULL,
    time    timestamp with time zone NOT NULL,
    CONSTRAINT "PK_save" PRIMARY KEY (save_id)
);

CREATE TABLE IF NOT EXISTS stakeholder
(
    id           uuid                  NOT NULL,
    name         character varying(50) NOT NULL,
    path_to_icon character varying(50) NOT NULL,
    CONSTRAINT "PK_stakeholder" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS subtask
(
    id                   uuid                  NOT NULL,
    affected_entity_id   uuid                  NOT NULL,
    name                 character varying(30) NOT NULL,
    "order"              smallint              NOT NULL,
    base_effectiveness   integer               NOT NULL,
    is_use_capacity_tool boolean               NOT NULL,
    CONSTRAINT "PK_subtask" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS subtask_capacity_tool
(
    id          uuid     NOT NULL,
    resource_id uuid,
    subtask_id  uuid     NOT NULL,
    capacity    smallint NOT NULL,
    CONSTRAINT "PK_subtask_capacity_tool" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS subtask_tool
(
    id          uuid NOT NULL,
    resource_id uuid NOT NULL,
    subtask_id  uuid NOT NULL,
    CONSTRAINT "PK_subtask_tool" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS task
(
    id          uuid                  NOT NULL,
    location_id uuid                  NOT NULL,
    name        character varying(30) NOT NULL,
    target      integer               NOT NULL,
    day_limit   smallint              NOT NULL,
    is_true     boolean               NOT NULL,
    CONSTRAINT "PK_task" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS tool
(
    resource_id  uuid                  NOT NULL,
    path_to_icon character varying(50) NOT NULL,
    CONSTRAINT "PK_tool" PRIMARY KEY (resource_id)
);

CREATE TABLE IF NOT EXISTS worker
(
    id                  uuid                  NOT NULL,
    name                character varying(30) NOT NULL,
    path_to_icon        text                  NOT NULL,
    effectiveness_coeff double precision      NOT NULL,
    CONSTRAINT "PK_worker" PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_player_settings_player_id" ON player_settings (player_id);